<a href="https://colab.research.google.com/github/anchalaug25/ml_anchal/blob/main/onehot_git.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from google.colab import files
uploaded=files.upload()

Saving cars1.csv to cars1.csv

In [ ]:
df=pd.read_csv("cars1.csv")

In [ ]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [ ]:
df["brand"].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Ambassador          4
Kia                 4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [ ]:
df["fuel"].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [ ]:
pd.get_dummies(df,columns=["fuel","brand"],drop_first=True)

,km_driven,owner,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,brand_Ashok,brand_Audi,brand_BMW,brand_Chevrolet,...,brand_Mitsubishi,brand_Nissan,brand_Opel,brand_Peugeot,brand_Renault,brand_Skoda,brand_Tata,brand_Toyota,brand_Volkswagen,brand_Volvo
0,145500,First Owner,450000,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,120000,Second Owner,370000,True,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
2,140000,Third Owner,158000,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,127000,First Owner,225000,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,120000,First Owner,130000,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8123,110000,First Owner,320000,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8124,119000,Fourth & Above Owner,135000,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8125,120000,First Owner,382000,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8126,25000,First Owner,290000,True,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
8127,25000,First Owner,290000,True,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False

In [ ]:
x = df.drop("selling_price", axis=1)

In [ ]:
y=df["selling_price"]

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x, y, test_size=0.2,random_state=51) # Added x and y as inputs to the function

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
ohe=OneHotEncoder(drop="first",sparse_output=False,)